[#3] 홈화면 조회 기능 개발
f-lab-edu/trend-pop pull request #4
Opened 2024-09-15 20:38 UTC by jiyoonkong

- 추천 팝업 목록 조회
- 인기 팝업 목록 조회
- 최근 조회한 팝업 목록 조회

2024-09-16 02:06 UTC, pjy1368 commented on src/main/java/com/trendpop/infrastructure/mapper/HomeMapper.java
> +    List<Store> findMostPopularStores();
가능한 Mapper도 성격에 맞게 분리하고, 최대한 단일 쿼리만 작성하여 애플리케이션에서 Mapper들간의 로직을 여러번 호출하여 조합할 수 있도록 해주세요!

2024-09-20 05:00 UTC, jiyoonkong commented on src/main/java/com/trendpop/infrastructure/mapper/HomeMapper.java
> +    List<Store> findMostPopularStores();
HomeMapper를 성격에 맞게 StoreMapper, StoreTypeMapper, LocationMapper, StorePhotoMapper, ReservationMapper, StoreViewHistoryMapper로 분리하고, HomeService에서 이를 호출하는 로직으로 수정했습니다.

2024-09-21 09:49 UTC, blue000927 requested changes

2024-09-21 09:49 UTC, blue000927 commented on src/main/java/com/trendpop/config/WebConfig.java
> +                .excludePathPatterns("/api/user/login", "/api/user/signup", "/api/home/**");
이렇게 일일이 다 추가하는건 귀찮을거같은데
addPathPatterns("/api/**")로 해놓고 includePathPatterns()로 로그인, 회원 가입 쪽 추가하는 방향으로 바꿔보면 어떨까요?

2024-09-21 09:49 UTC, blue000927 commented on src/main/java/com/trendpop/infrastructure/mapper/HomeMapper.java
> +public interface HomeMapper { // HomeMapper 삭제 예정.
이렇게 ~~할 예정의 경우 주석 앞에 TODO를 붙입니다.
(ex. TODO: HomeMapper 삭제 예정)
더불어, TODO가 계속 남아있는 것을 방지하기 위하여 작업자와 마감일도 기입해두는 편입니다.
(ex. TODO(@blue): HomeMapper 삭제 예정. Due Date: 2024.10.01)

2024-09-21 09:49 UTC, blue000927 commented on src/main/java/com/trendpop/infrastructure/mapper/ReservationMapper.java
> +    List<StoreReservationCount> findTop10StoreReservationCounts();
메서드명만 보고는 쿼리에 deleted=false, status != cancelled 조건이 들어갈 것이라고 판단하기 어려워 보이네요.
이때에는 메서드 명을 고쳐볼 수 있고, 메서드 명은 유지하면서 조건 파라미터를 받는 방법이 있습니다.
기본적으로 Mapper만 보더라도 어떠한 쿼리가 있을지 유추가 되어야 합니다!

2024-09-21 09:49 UTC, blue000927 commented on src/main/java/com/trendpop/infrastructure/mapper/StoreMapper.java
> +    List<String> findRecommendedStoreIds();
ditto: 메서드 명으로는 is_active=true, order by 조건이 있다고 추측할 수 없음.

2024-09-21 09:49 UTC, blue000927 commented on src/main/java/com/trendpop/infrastructure/mapper/StoreMapper.java
> +    List<Store> findStoresByIds(@Param("storeIds") List<String> storeIds);
ditto: 메서드 명으로는 deleted 조건이 있다고 추측할 수 없음.

2024-09-21 09:49 UTC, blue000927 commented on src/main/java/com/trendpop/infrastructure/mapper/StorePhotoMapper.java
> +    List<StorePhoto> findMainStorePhotosByIds(@Param("storeIds") List<String> storeIds);
서브 쿼리는 mapper에서 사용하지 않았으면 합니다!

2024-09-21 09:49 UTC, blue000927 commented on src/main/resources/db/schema.sql
users 외의 신규 추가한 테이블도 DDL 작성 부탁드립니다.

2024-09-21 09:49 UTC, blue000927 commented on src/main/java/com/trendpop/domain/model/StoreInfo.java
> +}
Store와 StoreInfo의 차이를 이름만 보면 잘 모르겠습니다! StoreInfo 내부를 보면 List<Store>를 가지고 있어서 더욱 이해가 잘 가지 않네요.

2024-09-21 09:49 UTC, blue000927 commented on src/main/java/com/trendpop/domain/model/StoreReservationCount.java
> +public record StoreReservationCount(String storeId, int reservationCount) {
꼭 별도 객체로 빼야 할까요? 필요한 곳에서 바로 `int reservationCount`로 받을 수 있지 않을까 싶어요.

2024-09-21 09:49 UTC, blue000927 commented on src/main/java/com/trendpop/domain/model/StorePhoto.java
> +}
우선 객체 및 테이블을 늘리기보다는 Store 하나에 넣어보면 어떨까요?
그리고 int order의 의미를 잘 모르겠네요.

2024-09-21 09:49 UTC, blue000927 commented on src/main/java/com/trendpop/domain/model/StoreType.java
> +}
그냥 Store 객체 안에 String type이 있으면 안되나요?

2024-09-21 09:49 UTC, blue000927 commented on src/main/java/com/trendpop/domain/model/Stores.java
> +}
Store vs Stores 어떤 차이인가요? 후자의 경우 List<Store>를 들고 있는 것으로 예상했는데 실제로 보니 Store와 유사한 필드들을 가지고 있네요.

2024-09-21 09:49 UTC, blue000927 commented on src/main/java/com/trendpop/presentation/controller/HomeController.java
> +public class HomeController {
프론트 입장에서 Home인 것이지, 서버에서까지 꼭 Home이라고 명명할 필요는 없는 것 같아요.
StoreController, LocationController, ReservationController 정도로 구분하여 각각 서비스도 나누고 Mapper도 나눠보면 좋겠습니다.

2024-09-21 09:49 UTC, blue000927 commented on src/main/java/com/trendpop/application/service/util/StoreInfoUtil.java
> +public class StoreInfoUtil {
1. Util 클래스의 의미는 무엇인가요?
2. Util 클래스의 용도는 무엇인가요?
3. 언제 Util 클래스를 사용하면 좋을까요?

2024-09-22 16:24 UTC, jiyoonkong commented on src/main/java/com/trendpop/config/WebConfig.java
> +                .excludePathPatterns("/api/user/login", "/api/user/signup", "/api/home/**");
includePathPatterns()는 제공되지 않는 메소드여서 addPathPatterns()에 인증이 필요한 경로를 추가하는 방향으로 하려했으나 api/User/{id} 같은 경우에는 패턴화가 안되고 api/User/**를 추가하면 "/api/user/login", "/api/user/signup"를 결국엔 또 exclude 해줘야 합니다.

2024-09-22 16:24 UTC, jiyoonkong commented on src/main/java/com/trendpop/infrastructure/mapper/HomeMapper.java
> +public interface HomeMapper { // HomeMapper 삭제 예정.
주석에 TODO 로 명시하였습니다.

2024-09-22 16:26 UTC, jiyoonkong commented on src/main/java/com/trendpop/infrastructure/mapper/ReservationMapper.java
> +    List<StoreReservationCount> findTop10StoreReservationCounts();
메서드 명에 Active 단어를 추가하여 findTop10ActiveStoreReservationCounts()로 수정했습니다.

2024-09-22 16:26 UTC, jiyoonkong commented on src/main/java/com/trendpop/infrastructure/mapper/StoreMapper.java
> +    List<String> findRecommendedStoreIds();
메서드 명을 findActiveRecommendedStoreIdsOrderByPriority()로 수정했습니다.

2024-09-22 16:27 UTC, jiyoonkong commented on src/main/java/com/trendpop/infrastructure/mapper/StoreMapper.java
> +    List<Store> findStoresByIds(@Param("storeIds") List<String> storeIds);
메서드 명을 findNonDeletedStoresByIds로 수정했습니다.

2024-09-22 16:28 UTC, jiyoonkong commented on src/main/java/com/trendpop/infrastructure/mapper/StorePhotoMapper.java
> +    List<StorePhoto> findMainStorePhotosByIds(@Param("storeIds") List<String> storeIds);
서브쿼리 대신 위 쿼리를 2개로 분리했습니다.

2024-09-22 16:28 UTC, jiyoonkong commented on src/main/resources/db/schema.sql
추가 작성 하였습니다.

2024-09-22 17:02 UTC, jiyoonkong commented on src/main/java/com/trendpop/domain/model/StoreInfo.java
> +}
Store는 Store 테이블 속성을 필드로 가지는 Store 클래스이고 StoreInfo는 조회된 stores 목록의 id와 매핑되는 StoreType, Location, StorePhoto 객체 리스트를 가지는 클래스입니다. 이 부분은 어떻게 수정해야 할 지 고민이 됩니다. StoreInfo 없이도 구현이 가능하다면 그렇게 수정해도 될까요?

2024-09-22 17:03 UTC, jiyoonkong commented on src/main/java/com/trendpop/domain/model/StoreReservationCount.java
> +public record StoreReservationCount(String storeId, int reservationCount) {
reservationCount 많은 순으로 storeId 를 정렬해야 해서 객체로 뺐습니다.

2024-09-22 17:08 UTC, jiyoonkong commented on src/main/java/com/trendpop/domain/model/StoreType.java
> +}
Store 객체 안에 Store Type 의 id는 포함되어 있으나 name까지 매핑하려고 따로 객체를 생성했다. stores 테이블과 store_types 테이블을 조인하는 쿼리를 분리하면서 위 객체도 새로 생성했습니다.

2024-09-22 17:09 UTC, jiyoonkong commented on src/main/java/com/trendpop/domain/model/StorePhoto.java
> +}
StorePhoto 테이블을 따로 만든 이유는 Store : StorePhoto 가 1:N 관계이기 때문입니다. order는 (화면에 보이게 될) 사진 순서 입니다.

2024-09-22 17:12 UTC, jiyoonkong commented on src/main/java/com/trendpop/domain/model/Stores.java
> +}
Stores는 기존 HomeMapper에서 사용했던 객체였으나 Store로 리팩토링 하면서 삭제할 예정입니다. TODO 주석 명시 추가했습니다.

2024-09-22 17:12 UTC, jiyoonkong commented on src/main/java/com/trendpop/presentation/controller/HomeController.java
> +public class HomeController {
StoreController, ReservationController로 구분했고 서비스도 구분하였습니다.

2024-09-22 17:23 UTC, jiyoonkong commented on src/main/java/com/trendpop/application/service/util/StoreInfoUtil.java
> +public class StoreInfoUtil {
1. 일반적으로 반복적으로 사용되는 공통 로직이나 다양한 곳에서 사용 가능한 유틸리티 메서드를 모아놓은 클래스입니다.
2. 다양한 곳에서 재사용 가능한 메서드를 모아 놓음으로써 코드의 중복을 줄이고 유지 보수를 쉽게 하기 위해 사용됩니다.
3. 특정 기능이 여러 클래스에서 공통적으로 필요하거나 독립적인 기능을 제공해야 할 때 Util 클래스를 사용하면 좋을 것 같습니다.
-> StoreInfoUtil.java는 현재 StoreService와 Reservation Service에서 호출하고 있습니다. 처음에 중복 코드들을 공통 로직으로 뺀 부분이여서 Util이라고 명명했는데 어떤 식으로 수정해야 할까요?

2024-09-25 04:27 UTC, blue000927 commented on src/main/java/com/trendpop/infrastructure/mapper/StorePhotoMapper.java
> +            "</script>")
하나의 쿼리는 하나의 일만 하도록 구성해 주세요!

현재 이 쿼리는 Store 리스트를 뽑고, 그 안에 Store마다 썸네일 이미지를 뽑으려는 두 행위가 혼재되어 있습니다.
이때는 다음과 같이 행위를 분리하여 쿼리를 작성하는 것이 좋습니다.

```java
store list를 먼저 뽑고
for (store store : stores) {
   mapper.findStorePhotoMinOrder(store);
}
```

2024-09-25 04:27 UTC, blue000927 commented on src/main/java/com/trendpop/application/service/util/StoreInfoUtil.java
> +public class StoreInfoUtil {
가능한 Util 클래스는 라이브러리 정도를 편하게 쓰기 위한 용도로 사용해 주시고, 나머지는 Service, Domain에 로직을 잘 위치시켜 보면 좋겠습니다

2024-09-25 04:27 UTC, blue000927 commented on src/main/java/com/trendpop/domain/model/StoreInfo.java
> +}
멘토링 시간때 말씀 드렸던대로 뭔가 Mapper에서 필드를 조합하여 새로운 객체를 매핑하도록 구성하지 말고, Store만 반환 Location만 반환 심플한 구조로 가면 좋겠습니다.

2024-09-25 04:27 UTC, blue000927 commented on src/main/java/com/trendpop/domain/model/StorePhoto.java
> +}
요건 굿입니다!

2024-09-25 04:27 UTC, blue000927 commented on src/main/java/com/trendpop/domain/model/StoreReservationCount.java
> +public record StoreReservationCount(String storeId, int reservationCount) {
이 부분도 해당 객체는 제거하도록 구성해보면 좋겠습니다

2024-09-25 04:27 UTC, blue000927 commented on src/main/java/com/trendpop/domain/model/StoreType.java
> +}
요거도 type은 하나로 지정하기로 했으니 Store 안에 넣어주세요

2024-09-29 08:48 UTC, jiyoonkong commented on src/main/java/com/trendpop/infrastructure/mapper/HomeMapper.java
> +public interface HomeMapper { // HomeMapper 삭제 예정.
삭제했습니다.

2024-09-29 08:50 UTC, jiyoonkong commented on src/main/java/com/trendpop/infrastructure/mapper/ReservationMapper.java
> +    List<StoreReservationCount> findTop10StoreReservationCounts();
List<String> findTop10ActiveStoreIdsOrderByReservationCounts() 로 store_id 리스트 리턴하는 메소드로 수정했습니다.

2024-09-29 08:51 UTC, jiyoonkong commented on src/main/java/com/trendpop/infrastructure/mapper/StoreMapper.java
> +    List<String> findRecommendedStoreIds();
List<String> findActiveRecommendedStoreIdsOrderByPriority() 로 store_id를 리턴하는 메소드로 수정하였습니다.

2024-09-29 08:52 UTC, jiyoonkong commented on src/main/java/com/trendpop/infrastructure/mapper/StoreMapper.java
> +    List<Store> findStoresByIds(@Param("storeIds") List<String> storeIds);
Store findNonDeletedStoreById(String storeId) Store 객체 리턴하는 메소드로 수정했습니다.

2024-09-29 08:54 UTC, jiyoonkong commented on src/main/java/com/trendpop/infrastructure/mapper/StorePhotoMapper.java
> +    List<StorePhoto> findMainStorePhotosByIds(@Param("storeIds") List<String> storeIds);
Integer findMinOrderByStoreIdNonDeleted(String storeId) : store photo의 minOrder 찾는 메소드
String findImageUrlByStoreIdAndOrder(String storeId, int minOrder): minOrder에 해당하는 photo url 찾는 메소드
로 2개로 분리 및 수정했습니다.

2024-09-29 08:55 UTC, jiyoonkong commented on src/main/resources/db/schema.sql
store_types 테이블 삭제, store에 location_detail 컬럼 (팝업스토어 상세 위치) 추가했습니다.

2024-09-29 08:56 UTC, jiyoonkong commented on src/main/java/com/trendpop/domain/model/StoreInfo.java
> +}
StoreInfo는 삭제하고 Store, StorePhoto, Location 객체를 활용해 구현했습니다.

2024-09-29 08:57 UTC, jiyoonkong commented on src/main/java/com/trendpop/domain/model/StoreReservationCount.java
> +public record StoreReservationCount(String storeId, int reservationCount) {
위 객체는 삭제했습니다!!

2024-09-29 08:58 UTC, jiyoonkong commented on src/main/java/com/trendpop/domain/model/StoreType.java
> +}
StoreType 객체 삭제했습니다.

2024-09-29 08:58 UTC, jiyoonkong commented on src/main/java/com/trendpop/domain/model/Stores.java
> +}
삭제했습니다.

2024-09-29 08:59 UTC, jiyoonkong commented on src/main/java/com/trendpop/application/service/util/StoreInfoUtil.java
> +public class StoreInfoUtil {
중복 로직을 Util이 아닌 StoreService 내에 **StoreResponse createStoreResponse(String storeId)** 메소드로 위치시켰습니다.

2024-09-29 09:01 UTC, jiyoonkong commented on src/main/java/com/trendpop/infrastructure/mapper/StorePhotoMapper.java
> +            "</script>")
**Integer findMinOrderByStoreIdNonDeleted(String storeId)** : store photo의 minOrder 찾는 메소드
**String findImageUrlByStoreIdAndOrder(String storeId, int minOrder)** : minOrder에 해당하는 photo url 찾는 메소드
2개로 분리 및 수정했습니다.

2024-09-30 12:34 UTC, blue000927 commented on src/main/java/com/trendpop/config/WebConfig.java
> +                .excludePathPatterns("/api/user/login", "/api/user/signup", "/api/home/**");
넵 지금 방식이 괜찮은거같아요!

2024-09-30 12:50 UTC, blue000927 reviewed
전체적으로 코드 퀄리티가 좋아졌네요 ㅎㅎ 한 번만 더 핑퐁해봅시다!

2024-09-30 12:50 UTC, blue000927 commented on src/main/java/com/trendpop/application/service/ReservationService.java
> +    }
롬복 써보면 어떨까요? (`@RequiredArgsConstructor`)
전체적으로 적용해보면 좋을듯합니다.

2024-09-30 12:50 UTC, blue000927 commented on src/main/java/com/trendpop/config/WebConfig.java
> +                .excludePathPatterns("/api/user/login", "/api/user/signup", "/api/home/**");
넵 다시 생각해보니 이 방향성이 좋아보입니다.

2024-09-30 12:50 UTC, blue000927 commented on src/main/java/com/trendpop/infrastructure/mapper/StoreMapper.java
> +    List<String> findActiveRecommendedStoreIdsOrderByPriority();
is_active, deleted는 다른건가요?

2024-09-30 12:50 UTC, blue000927 commented on src/main/java/com/trendpop/infrastructure/mapper/StoreMapper.java
> +    Store findNonDeletedStoreById(String storeId);
소프트 딜리트다보니 메서드명을 짓기 애매한 점이 있군요.
기본적으로 메서드를 findXXX로 작성하면 deleted=false로 하고, 특별히 deleted=true이거나 deleted=false와 deleted=true를 아우를 경우만 메서드를 다르게 지어보면 어떨까 해요.

가령 지금 메서드는 NonDeleted가 아닌 findStoreById() 요런 식으로 쓰는거죠!
(단, 쿼리에 deleted = false 조건 추가해야 합니다.)

2024-09-30 12:50 UTC, blue000927 commented on src/main/java/com/trendpop/infrastructure/mapper/StorePhotoMapper.java
> +    String findImageUrlByStoreIdAndOrder(String storeId, int minOrder);
확장성을 위해 반환 타입은 StorePhoto로 하면 좋겠습니다.

2024-09-30 12:50 UTC, blue000927 commented on src/main/java/com/trendpop/infrastructure/mapper/StoreViewHistoryMapper.java
> +    List<StoreViewHistory> findRecentlyViewedStoresByUserId(@Param("userId") String userId);
가장 최근에 view 한 것이면 viewed_at 기준으로 가장 앞 레코드를 뽑으면 될 것 같은데, MAX(viewd_at)을 해야하는 이유가 뭔가요?

2024-09-30 12:50 UTC, blue000927 commented on src/main/java/com/trendpop/application/service/ReservationService.java
> +    private final StoreService storeService;
가능한 Service끼리는 의존하지 않는 것이 좋긴한데, 만약 의존해야 한다면 서로 순환 참조가 되는 현상은 피해주셔야 합니다!

2024-09-30 12:50 UTC, blue000927 commented on src/main/java/com/trendpop/domain/model/Store.java
> +                    , LocalTime openTime, LocalTime closeTime, int price, boolean reserveClosed, String locationDetail) {
locationDetail 같은건 enum으로 관리하는 것이 좋지 않을까요?

2024-09-30 12:50 UTC, blue000927 commented on src/main/java/com/trendpop/presentation/controller/ReservationController.java
> +        return reservationService.getMostPopularStores();
API는 가장 인기 있는 예약으로 읽히는데, 반환 타입이 Store인건 어색하지 않을까요?

2024-10-03 08:34 UTC, jiyoonkong commented on src/main/java/com/trendpop/application/service/ReservationService.java
> +    }
롬복 @RequiredArgsConstructor 사용해 보았습니다!

2024-10-03 08:35 UTC, jiyoonkong commented on src/main/java/com/trendpop/infrastructure/mapper/StoreMapper.java
> +    List<String> findActiveRecommendedStoreIdsOrderByPriority();
같은 의미여서 delete로 테이블 컬럼 명, 쿼리 수정했습니다.

2024-10-03 08:35 UTC, jiyoonkong commented on src/main/java/com/trendpop/infrastructure/mapper/StoreMapper.java
> +    Store findNonDeletedStoreById(String storeId);
메소드 명 전체적으로 수정했습니다!

2024-10-03 08:36 UTC, jiyoonkong commented on src/main/java/com/trendpop/infrastructure/mapper/StorePhotoMapper.java
> +    String findImageUrlByStoreIdAndOrder(String storeId, int minOrder);
- Integer findMinOrderByStoreIdNonDeleted(String storeId); 이 메소드는 MIN 값 뽑는 쿼리여서 Integer로 놔두었습니다.
- String findImageUrlByStoreIdAndOrder(String storeId, int minOrder); 이 메소드는 반환값 StorePhoto로 수정했습니다.

2024-10-03 08:38 UTC, jiyoonkong commented on src/main/java/com/trendpop/infrastructure/mapper/StoreViewHistoryMapper.java
> +    List<StoreViewHistory> findRecentlyViewedStoresByUserId(@Param("userId") String userId);
가장 최근에 view 한 store 목록 10개 중에서 중복되는 store가 있을 경우 중복을 제거하고 10개 리스트를 조회하고 싶어서입니다.

2024-10-03 08:39 UTC, jiyoonkong commented on src/main/java/com/trendpop/application/service/ReservationService.java
> +    private final StoreService storeService;
넵!!

2024-10-03 08:41 UTC, jiyoonkong commented on src/main/java/com/trendpop/domain/model/Store.java
> +                    , LocalTime openTime, LocalTime closeTime, int price, boolean reserveClosed, String locationDetail) {
locationDetail에는 '서울시 영등포구 여의대로 108 더현대서울 지하 1층' 이런 식으로 풀 주소값을 넣는 컬럼이기에 String으로 하였습니다.

2024-10-03 08:43 UTC, jiyoonkong commented on src/main/java/com/trendpop/presentation/controller/ReservationController.java
> +        return reservationService.getMostPopularStores();
반환값은 Store인게 의도한 부분은 맞습니다! (예약수 기준으로 가장 인기있는 Store)
url을 /most-popular-stores 로 변경했습니다.

2024-10-04 13:21 UTC, blue000927 approved these changes
고생하셨어요~!

2024-10-04 13:21 UTC, blue000927 commented on src/main/java/com/trendpop/infrastructure/mapper/StoreMapper.java
> +    List<String> findRecommendedStoreIdsOrderByPriority();
recommended_stores를 관리하는 RecommendedStoreMapper가 있으면 합니다. (+ RecommnededStore 엔티티도)

2024-10-04 13:21 UTC, blue000927 commented on src/main/java/com/trendpop/infrastructure/mapper/StorePhotoMapper.java
> +    Integer findMinOrderByStoreId(String storeId);
`select * from store_photos where store_id = #{storeId} and deleted = false order by `order` limit 1`
이렇게 해도 되지 않을까요?

2024-10-04 17:12 UTC, jiyoonkong commented on src/main/java/com/trendpop/infrastructure/mapper/StoreMapper.java
> +    List<String> findRecommendedStoreIdsOrderByPriority();
RecommendedStoreMapper, RecommnededStore  추가했습니다.

2024-10-04 17:12 UTC, jiyoonkong commented on src/main/java/com/trendpop/infrastructure/mapper/StorePhotoMapper.java
> +    Integer findMinOrderByStoreId(String storeId);
위 쿼리로 변경 후 StorePhoto 반환하도록 수정했습니다.

2024-10-04 17:13 UTC, merged